name: Build and Deploy

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/web/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Copy Compose Files to Server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker/"
          target: "${{ secrets.SERVER_PATH }}"

      - name: Deploy
        uses: appleboy/ssh-action@v1.2.5
        env:
          APP_VERSION: ${{ github.ref_name }}
          APPTOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          USERNAME: ${{ github.actor }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DJANGO_USER: ${{ secrets.DJANGO_USER }}
          DJANGO_PASS: ${{ secrets.DJANGO_PASS }}
          DJANGO_EMAIL: ${{ secrets.DJANGO_EMAIL }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          envs: APP_VERSION,APPTOKEN,REPO_NAME,USERNAME,POSTGRES_USER,POSTGRES_PASSWORD,POSTGRES_DB,DJANGO_USER,DJANGO_PASS,DJANGO_EMAIL
          script: |
            # 1. Login to GHCR
            echo $APPTOKEN | docker login ghcr.io -u $USERNAME --password-stdin

            # 2. Navigate to deployment directory
            cd ${{ secrets.SERVER_PATH }}/docker

            cat <<EOF > django.env
            DJANGO_DATABASE_HOST=medna_metadata_pgdb
            DJANGO_DATABASE_PORT=5432
            DJANGO_DATABASE_NAME=$POSTGRES_DB
            DJANGO_DATABASE_USERNAME=$POSTGRES_USER
            DJANGO_DATABASE_PASSWORD=$POSTGRES_PASSWORD
            DJANGO_SUPERUSER_PASSWORD=$DJANGO_PASS
            DJANGO_SUPERUSER_USERNAME=$DJANGO_USER
            DJANGO_SUPERUSER_EMAIL=$DJANGO_EMAIL
            EOF

            # 3. Pull images using the version variable
            docker compose -f docker-compose.yml pull

            # 4. Start the rest of the app
            docker compose -f docker-compose.yml up -d
